PRODUCT_VERSION_MAJOR = 22
PRODUCT_VERSION_MINOR = 0

LINEAGE_BUILDTYPE := UNOFFICIAL

CUSTOM_VERSION = v15.0
CUSTOM_EDITION := GAPPS
CUSTOM_BUILD_DATETIME := $(shell date +%s)
CUSTOM_BUILD_DATE := $(shell date -d @$(CUSTOM_BUILD_DATETIME) +"%Y%m%d-%H%M%S")

# Internal version
LINEAGE_VERSION := AresOS-$(CUSTOM_VERSION)-$(CUSTOM_EDITION)-$(CUSTOM_BUILD_DATE)

# Display version
LINEAGE_DISPLAY_VERSION := AresOS-$(CUSTOM_VERSION)-$(CUSTOM_EDITION)-$(CUSTOM_BUILD_DATE)

# LineageOS version properties
PRODUCT_SYSTEM_PROPERTIES += \
    ro.lineage.version=$(LINEAGE_VERSION) \
    ro.lineage.display.version=$(LINEAGE_DISPLAY_VERSION) \
    ro.lineage.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.lineage.releasetype=$(LINEAGE_BUILDTYPE) \
    ro.modversion=$(LINEAGE_VERSION)
